env: ../../environment.yml
output_dir: /data/processed_datasets/processed_datasets/ehr_foundation_data/ohdsi_cumc_deid/ohdsi_cumc_deid_2023q4r3_corebehrt/corebehrt_data
tokenized_dir_name: "tokenized"
paths:
  run_name: "_pretrain"
  save_features_dir_name: "features" # saves in this directory on azure. If not provided use run_name.
loader:
  # can provide formatted data or features
  data_dir:  /data/processed_datasets/processed_datasets/ehr_foundation_data/ohdsi_cumc_deid/ohdsi_cumc_deid_2023q4r3_corebehrt/
  concepts: [
    condition_occurrence, drug_exposure
  ]
  batch_size: 1000000000
  chunksize: 30000000

features:
  age: 
    round: 2
  abspos:
    year: 2023
    month: 12
    day: 31
  segment: true
  background: ['GENDER']

tokenizer:
  sep_tokens: true
  cls_token: true
  truncation: null
  #cutoffs:
   # D: 3 # diagnosis
   # M: 4 # medication

excluder:
  min_len: 2

handler:
  min_age: -1
  max_age: 120
predefined_splits_dir: /data/processed_datasets/processed_datasets/ehr_foundation_data/ohdsi_cumc_deid/ohdsi_cumc_deid_2023q4r3_corebehrt/splits/
# can be a list
# exclude_pids: outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test/test_pids.pt
# assigned_pids: 
  # can be a list
  # pretrain: 
  #  - outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test/fold_1/val_pids.pt
#predefined_splits_dir: ../outputs/data_icd10/tokenized #../outputs/features_test/tokenized

